services:
  - type: web
    name: inventory-system-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-system-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://inventory-system-web-ehzg.onrender.com

  - type: web
    name: inventory-system-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    envVars:
      - key: VITE_API_BASE
        value: https://inventory-system-api-mzjz.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: inventory-system-db
    plan: free
    databaseName: inventory_system
    user: inventory_system
